apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: SECRET_KEY
              value: "test-secret"
            - name: MONGO_URI
              value: "mongodb://test"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-service
  template:
    metadata:
      labels:
        app: messaging-service
    spec:
      containers:
        - name: messaging-service
          image: messaging-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
          env:
            - name: AUTH_URL
              value: "http://auth-service:5001"

---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  selector:
    app: messaging-service
  ports:
    - port: 5002
      targetPort: 5002
  type: ClusterIP


---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: gateway-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: gateway-config
          configMap:
            name: gateway-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;

        # route: /auth → auth-service:5001
        location /auth/ {
          proxy_pass http://auth-service:5001/;
        }

        # route: /chat → messaging-service:5002
        location /chat/ {
          proxy_pass http://messaging-service:5002/;
        }
      }
    }
