FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Environment variables (NO SECRETS)
ENV FLASK_ENV=production
ENV PORT=5002

EXPOSE 5002

CMD ["python", "main.py"]
